//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.u8DevServiceSoap")]
    public interface u8DevServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getDocument(string domcumentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getDocumentAsync(string domcumentName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAskCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAskCount(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAskCount", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAskCountAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface u8DevServiceSoapChannel : WindowsFormsApplication2.ServiceReference1.u8DevServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class u8DevServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication2.ServiceReference1.u8DevServiceSoap>, WindowsFormsApplication2.ServiceReference1.u8DevServiceSoap {
        
        public u8DevServiceSoapClient() {
        }
        
        public u8DevServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public u8DevServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public u8DevServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public u8DevServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getDocument(string domcumentName) {
            return base.Channel.getDocument(domcumentName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getDocumentAsync(string domcumentName) {
            return base.Channel.getDocumentAsync(domcumentName);
        }
        
        public System.Data.DataSet getAskCount(string username) {
            return base.Channel.getAskCount(username);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAskCountAsync(string username) {
            return base.Channel.getAskCountAsync(username);
        }
    }
}
